### ISSUE TITLE
Test kitchen fails on macOS using Chef Client 13.0.118

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/vsts-agent-cookbook#4]
I was receiving an error using the declared omnibus version of 12.4.3, so I modified `.kitchen.yml` to use the latest version. Now receiving the following error during the agent removal test:

```       Recipe: osx-basic::default
         * vsts_agent[osx_osx-basic-10105_01] action remove

           ================================================================================
           Error executing action `remove` on resource 'vsts_agent[osx_osx-basic-10105_01]'
           ================================================================================

           NameError
           ---------
           uninitialized constant Chef::Resource::VstsAgent

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/vsts_agent/providers/default.rb:14:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/osx-basic/recipes/default.rb

            13: vsts_agent agent1_name do
            14:   vsts_token node['vsts_agent_test']['vsts_token']
            15:   action :remove
            16: end
            17:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/osx-basic/recipes/default.rb:13:in `from_file'

           vsts_agent("osx_osx-basic-10105_01") do
             action [:remove]
             default_guard_interpreter :default
             declared_type :vsts_agent
             cookbook_name "osx-basic"
             recipe_name "default"
             vsts_token "nkxk67z764a3wz5p7km3xhh3ykvofupta3nywzzpbzkjtxbkfevq"
             agent_name "osx_osx-basic-10105_01"
           end

           System Info:
           ------------
           chef_version=13.0.118
           platform=mac_os_x
           platform_version=10.10.5
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
           program_name=chef-client worker: ppid=643;start=12:13:44;
           executable=/opt/chef/bin/chef-client
```
The full log is [here](https://github.com/Microsoft/vsts-agent-cookbook/files/971764/osx-basic-10105.log.zip)

FYI, I've revoked the token shown.

**Comment by ivadim** [comment]
I fixed issue related to Chef 13. @americanhanko could you please try cookbook version 1.2.0 from the master?

**Comment by americanhanko** [comment]
This issue is resolved, thanks! There is another problem with sensitive output, however. Opening a new issue.
